language: c
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake libglib2.0-dev libgee-0.8
         valac-0.22

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && cd test && ./test-log4vala

